### PR TITLE
Add "__init__.py" and fix Import/Export errors when no ActiveDocument

### PR DESCRIPTION
**Pull request by allilou**
Some fixes for errors rised when running the Workbench on Debian 10 (freeCAD 0.18)

### CODE REVIEW

**Comment by kuttamuwa** [comment]
Thanks for your work. I also made pull requests about pep8. I guess I forgot to create pull request couple months ago :(

**Comment by HakanSeven12** [comment]
I don't work on this project anymore 🙂 https://forum.freecadweb.org/viewtopic.php?f=8&t=34371&start=110

**Comment by allilou** [comment]
I'm interested to continue working on this project.
I it possible to have write access to the main repository, or maybe you can transfer this repository to my account if you don't want it anymore.

**Comment by HakanSeven12** [comment]
I added you as collaborator.

**Pull request merged**
